async def discounts_send(bot, callback_query):
    await bot.send_message(callback_query.from_user.id, 'Акции Аква-мобиль:')
    await bot.send_photo(callback_query.from_user.id, open('./discounts_parsers/aquamobil/aquamobil_1.png', 'rb'))
    await bot.send_photo(callback_query.from_user.id, open('./discounts_parsers/aquamobil/aquamobil_2.png', 'rb'))
    await bot.send_photo(callback_query.from_user.id, open('./discounts_parsers/aquamobil/aquamobil_3.png', 'rb'))
    await bot.send_photo(callback_query.from_user.id, open('./discounts_parsers/aquamobil/aquamobil_4.jpg', 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Чебаркульского истока:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/chebarkul/chebarkul_1.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/chebarkul/chebarkul_2.jpg", 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Кристальной:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/crystal/crystal.png", 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Горного Оазиса:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/gorny/gorny_1.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/gorny/gorny_2.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/gorny/gorny_3.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/gorny/gorny_4.jpg", 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Воды Люкс:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_0.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_1.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_2.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_3.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_4.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_5.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_6.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_7.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_8.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_9.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_10.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_11.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_12.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_13.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_14.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_15.png", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/luxe/luxe_16.png", 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Ниагары:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_0.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_1.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_2.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_3.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_4.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_5.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_6.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_7.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_del_8.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_1.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_2.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_3.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_4.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_5.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_6.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_7.jpg", 'rb'))
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/niagara/niagara_store_8.jpg", 'rb'))
    await bot.send_message(callback_query.from_user.id, 'Акции Живой:')
    await bot.send_photo(callback_query.from_user.id, open("./discounts_parsers/zhivaya/zhivaya.png", 'rb'))


    