from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
from urllib.request import urlretrieve

def parser():
    driver = webdriver.Firefox()
    driver.get("https://l-w.ru/promo/")
    img_element = driver.find_element(By.XPATH, '/html/body/div[4]/div[2]/div[4]/div/div/div[1]/img')
    img_url = img_element.get_attribute('src')
    urlretrieve(img_url, "luxe_0.jpg")
    BeautifulSoup(driver.page_source, 'html.parser')
    driver.find_element(By.CLASS_NAME, 'fancybox-close-small').click()
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[1]')
    element.screenshot("luxe_1.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[2]')
    element.screenshot("luxe_2.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[3]')
    element.screenshot("luxe_3.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[4]')
    element.screenshot("luxe_4.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[5]')
    element.screenshot("luxe_5.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[6]')
    element.screenshot("luxe_6.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[7]')
    element.screenshot("luxe_7.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[8]')
    element.screenshot("luxe_8.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[9]')
    element.screenshot("luxe_9.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[10]')
    element.screenshot("luxe_10.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[11]')
    element.screenshot("luxe_11.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[12]')
    element.screenshot("luxe_12.png")
    driver.get("https://l-w.ru/promo/?PAGEN_1=2")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[1]')
    element.screenshot("luxe_13.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[2]')
    element.screenshot("luxe_14.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[3]')
    element.screenshot("luxe_15.png")
    element = driver.find_element(By.XPATH, '/html/body/div[1]/main/div/div/div[2]/a[4]')
    element.screenshot("luxe_16.png")
    driver.close()
    return